### ISSUE TITLE
Text posts should contain attribution

### ISSUE THREAD

**Issue by Zamboniman** [v1nsai/red2lem#2]
Text posts crossposted over should contain an attribution so folks know who wrote them. Something like:

"Originally posted at Reddit by /u/blahblahblah"

before the text or wherever.

**Comment by minorsecond** [comment]
This PR adds author name to the post: https://github.com/v1nsai/red2lem/pull/4

**Comment by Zamboniman** [comment]
That's great, thanks.

**Comment by Zamboniman** [comment]
@minorsecond I'm trying out your pull request now. Looks good so far!

**Comment by v1nsai** [comment]
Tried out the PR too, merged and closed so I'm going to close this issue too.  Thanks @minorsecond !
